2021-04-28 11:12:51,650 - test - INFO - Start
2021-04-28 11:12:51,651 - test - WARNING - Something maybe fail.
2021-04-28 11:12:51,652 - test - ERROR - Faild to get result
Traceback (most recent call last):
  File "testLog2.py", line 16, in <module>
    result = 10 / 0
ZeroDivisionError: division by zero
2021-04-28 11:12:51,657 - test - INFO - Finished
